### ISSUE TITLE
Tests in native mode fail

### ISSUE THREAD

**Issue by zakkak** [Karm/collector#32]
Running:

```
./mvnw -Dnative clean verify -Dquarkus.native.container-runtime=podman
```

fails with:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.redhat.quarkus.mandrel.collector.AuthTestIT
WARN[0824] IdleTracker: StateClosed transition by connection marked un-managed  X-Reference-Id=0xc001188000
WARN[0824] Requested oom_score_adj=0 is lower than the current one, changing to 200 
2024-06-14 10:06:50,878 WARN  [io.qua.con.build] (main) The 'quarkus.http.auth.form.redirect-after-login' config property is deprecated and should not be used anymore
2024-06-14 10:06:51,207 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-18) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2024-06-14 10:06:51,368 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-18) Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:/run/user/1000/podman/podman.sock
2024-06-14 10:06:51,369 INFO  [org.tes.DockerClientFactory] (build-18) Docker host IP address is localhost
2024-06-14 10:06:51,426 INFO  [org.tes.DockerClientFactory] (build-18) Connected to docker: 
  Server Version: 5.0.3
  API Version: 1.41
  Operating System: fedora
  Total Memory: 63424 MB
2024-06-14 10:06:51,427 WARN  [org.tes.uti.ResourceReaper] (build-18) 
********************************************************************************
Ryuk has been disabled. This can cause unexpected behavior in your environment.
********************************************************************************
2024-06-14 10:06:51,428 INFO  [org.tes.DockerClientFactory] (build-18) Checking the system...
2024-06-14 10:06:51,428 INFO  [org.tes.DockerClientFactory] (build-18) ✔︎ Docker server version should be at least 1.6.0
2024-06-14 10:06:51,432 INFO  [org.tes.ima.PullPolicy] (build-18) Image pull policy will be performed by: DefaultPullPolicy()
2024-06-14 10:06:51,432 INFO  [org.tes.uti.ImageNameSubstitutor] (build-18) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2024-06-14 10:06:51,508 INFO  [tc.mar.3] (build-18) Creating container for image: mariadb:10.3
2024-06-14 10:06:51,514 WARN  [tc.mar.3] (build-18) Reuse was requested but the environment does not support the reuse of containers
To enable reuse of containers, you must set 'testcontainers.reuse.enable=true' in a file located at /home/zakkak/.testcontainers.properties
2024-06-14 10:06:51,721 INFO  [tc.mar.3] (build-18) Container mariadb:10.3 is starting: 74a37d05a474d189a59742f730281dc5f315402ded07d5346137d3360b791183
2024-06-14 10:06:51,955 INFO  [tc.mar.3] (build-18) Waiting for database connection to become available at jdbc:mariadb://localhost:49158/quarkus using query 'SELECT 1'
2024-06-14 10:06:57,558 INFO  [tc.mar.3] (build-18) Container mariadb:10.3 started in PT6.049433722S
2024-06-14 10:06:57,558 INFO  [tc.mar.3] (build-18) Container is started (JDBC URL: jdbc:mariadb://localhost:49158/quarkus)
2024-06-14 10:06:57,558 INFO  [io.qua.dev.mar.dep.MariaDBDevServicesProcessor] (build-18) Dev Services for MariaDB started.
2024-06-14 10:06:57,559 INFO  [io.qua.dat.dep.dev.DevServicesDatasourceProcessor] (build-18) Dev Services for default datasource (mariadb) started - container ID is 74a37d05a474
2024-06-14 10:06:57,761 WARN  [io.qua.con.build] (main) The 'quarkus.http.auth.form.redirect-after-login' config property is deprecated and should not be used anymore
Executing "/home/zakkak/code/collector/target/collector-1.0.0-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/home/zakkak/code/collector/target/quarkus.log -Dquarkus.log.file.enable=true -Dquarkus.log.category."io.quarkus".level=INFO -Dquarkus.datasource.password=quarkus -Dquarkus.native.container-runtime=podman -Dquarkus.datasource.db-kind=mariadb -Dquarkus.datasource.jdbc.url=jdbc:mariadb://localhost:49158/quarkus -Dquarkus.datasource.username=quarkus -Dquarkus.datasource.devservices.port=49158 -Dquarkus.datasource.devservices.image-name=mariadb:10.3"
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-06-14 10:06:58,032 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.RuntimeException: jakarta.persistence.PersistenceException: [PersistenceUnit: <default>] Unable to build Hibernate SessionFactory
	at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:78)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:101)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits1868654632.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits1868654632.deploy(Unknown Source)
	... 7 more
Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: <default>] Unable to build Hibernate SessionFactory
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:126)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:86)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:74)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:156)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:64)
	at java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [build_perf_stats]
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:134)
	at org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:46)
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:97)
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:75)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:293)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:143)
	at java.base@21.0.3/java.util.HashMap.forEach(HashMap.java:1429)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:140)
	at io.quarkus.hibernate.orm.runtime.observers.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:21)
	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:293)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
	... 9 more

Application was not started: 2024-06-14 10:06:58,032 b226b5640024 [68] ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
Failed to launch the application. The application logs can be found at: /home/zakkak/code/collector/target/quarkus.log
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 7.719 s <<< FAILURE! - in com.redhat.quarkus.mandrel.collector.AuthTestIT
[ERROR] com.redhat.quarkus.mandrel.collector.AuthTestIT.userSignUpOK  Time elapsed: 0.005 s  <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
Caused by: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details

[INFO] Running com.redhat.quarkus.mandrel.collector.TokenTestIT
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.002 s - in com.redhat.quarkus.mandrel.collector.TokenTestIT
[INFO] Running com.redhat.quarkus.mandrel.collector.report.ExperimentTestIT
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s - in com.redhat.quarkus.mandrel.collector.report.ExperimentTestIT
[INFO] Running com.redhat.quarkus.mandrel.collector.report.endpoints.GraalImageStatsResourceTestIT
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 0.135 s - in com.redhat.quarkus.mandrel.collector.report.endpoints.GraalImageStatsResourceTestIT
[INFO] Running com.redhat.quarkus.mandrel.collector.report.endpoints.ImageStatsResourceTestIT
[WARNING] Tests run: 11, Failures: 0, Errors: 0, Skipped: 11, Time elapsed: 0.004 s - in com.redhat.quarkus.mandrel.collector.report.endpoints.ImageStatsResourceTestIT
[INFO] Running com.redhat.quarkus.mandrel.collector.report.endpoints.ResourceErrorsTestIT
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s - in com.redhat.quarkus.mandrel.collector.report.endpoints.ResourceErrorsTestIT
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AuthTestIT.userSignUpOK » Runtime java.lang.IllegalStateException: Unable to d...
[INFO] 
[ERROR] Tests run: 21, Failures: 0, Errors: 1, Skipped: 20
```

**Comment by Karm** [comment]
@zakkak There is "no issue". The thing is that as you can see, Quarkus is trying to start the native test app in *prod* profile, while the java one executed in *test* profile. To mitigate this, we have been using the following to test the Collector:

```
$ export JAVA_HOME=/home/karm/X/JDKs/mandrel-java21-23.1.3.1-Final/;export GRAALVM_HOME=${JAVA_HOME};export PATH=${JAVA_HOME}/bin:${PATH}
$ export DOCKER_HOST=unix:///run/user/${UID}/podman/podman.sock
$ ./mvnw -Dnative clean verify -Dquarkus.native.container-runtime=podman -Dquarkus.profile=test

...
[INFO] Results:
[INFO] 
[INFO] Tests run: 21, Failures: 0, Errors: 0, Skipped: 0
[INFO] 

```

**Comment by Karm** [comment]
@zakkak You can note in the GHA workflow that the one that deploys to production builds the native image twice. Once for test and once for deployment.
